# 1.Create a 10x10 array with random values and find the minimum and maximum values

In [1]:
import numpy as np

In [2]:
X=np.random?

In [3]:
X=np.random.randint?

In [10]:
X=np.random.randint(100,size=(10,10))
X

array([[72, 49, 74, 69, 19,  9, 84, 61, 72, 14],
       [ 5, 77, 65, 48, 15, 88, 69, 83, 13, 83],
       [45, 19, 80, 18, 63, 48, 86, 25, 80, 54],
       [22,  0, 28, 50, 71, 18, 17, 29, 77, 37],
       [41, 45, 75,  6, 58, 38, 21, 56, 55, 30],
       [42, 91, 57, 98, 64, 48, 74,  2, 98, 67],
       [97, 37, 58, 40, 98, 42,  1, 65, 69, 32],
       [ 0, 79, 81, 50, 99, 20, 27,  9,  7, 35],
       [16, 62, 18, 99, 64, 49, 49, 82, 51, 75],
       [97, 91, 91, 75, 18, 61, 78,  1, 33, 54]])

In [11]:
print(np.min(X))
print(np.max(X))

0
99


# Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
X=np.arange(9)
X = X.reshape((3,3))
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Create a 3x3 identity matrix

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a 5x5 random matrix

In [16]:
np.random.randint(9,size=(5,5))

array([[8, 6, 4, 0, 1],
       [1, 4, 7, 1, 5],
       [0, 8, 3, 0, 6],
       [5, 6, 8, 7, 2],
       [0, 8, 6, 8, 4]])

# create diagonal matrix 6 x 6 with np.tri function.

In [24]:
# np.tri(6,6,0)
np.subtract(np.tri(6,6,0),np.tri(6,6,-1))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Create a 1-D array of 20 evenly spaced elements between 10. and 20., inclusive. (linspace)

In [23]:
np.linspace(10.,20.,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

# Create one 3 x 4 random matrix and one 3x4 identity matrix - Perform add(), subtract(), multiply() and dot().

In [29]:
x = np.random.randint(12,size=(3,4))
y = np.random.randint(12,size=(3,4))
np.add(x,y)

array([[ 9,  2, 15,  6],
       [11, 12,  3, 10],
       [ 6,  6,  6,  5]])

In [30]:
np.subtract(x,y)

array([[-7,  0,  1,  0],
       [ 3, -6,  1, -6],
       [ 4,  6,  6,  3]])

In [32]:
np.multiply(x,y)

array([[ 8,  1, 56,  9],
       [28, 27,  2, 16],
       [ 5,  0,  0,  4]])

In [34]:
np.dot(x,np.transpose(y))

array([[ 74,  45,   4],
       [ 79,  73,   9],
       [100, 112,   9]])