In [2]:
import numpy as np

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.arange(10)

In [6]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
arr2 = arr.reshape(5,2)
print(arr2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
print(f"Its an {arr.ndim}D array")

Its an 1D array


In [17]:
print(f"Its an {arr2.ndim}D array")

Its an 2D array


In [19]:
arr3 = np.arange(12)
arr3 = arr3.reshape(3,2,2)
print(arr3)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [20]:
print(f"Its an {arr3.ndim}D array")

Its an 3D array


In [21]:
arr4 = arr**2
print(arr4)

[ 0  1  4  9 16 25 36 49 64 81]


In [22]:
arr5 = arr+1
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
zero = np.zeros((5,2))
print(zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [25]:
one = np.ones((5,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
print(arr2[:,0])#first col of arr2

[0 2 4 6 8]


In [28]:
boolarr = arr2>5
boolarr

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [29]:
print(arr2[2,1])

5


In [32]:
arr6 = np.arange(24)
arr6 = arr6.reshape(12,1,2)
print(arr4)

[[[ 0  1]]

 [[ 2  3]]

 [[ 4  5]]

 [[ 6  7]]

 [[ 8  9]]

 [[10 11]]

 [[12 13]]

 [[14 15]]

 [[16 17]]

 [[18 19]]

 [[20 21]]

 [[22 23]]]


In [39]:
#WAP to transpose the 3X3 matrix
a=np.arange(1,18,2)
a = a.reshape(3,3)
print(a)

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]


In [40]:
a = a.transpose()
print(a)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
